census/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", views.home, name = "home"), 
    path("login", views.log_in, name='login'),
    path("empadron/logout", views.log_out, name = "logout"),

    path("empadron", views.empadron, name = "empadron"),

    path("voting-sheet", views.votingSheet, name = "voting-sheet"),
    path("voting-sheet/history", views.votingSheet_history, name = "voting-sheet-history"),

    path("voting-sheet/generate", views.votingSheet_generate, name = "voting-sheet-generate"),
    path("voting-sheet/fill/<str:id_sheet>", views.votingSheet_fill, name = "voting-sheet-fill"),
    path("voting-sheet/candidates/<str:id_sheet>", views.votingSheet_candidates, name = "voting-sheet-candidates"),

    path("voting-sheet/validate", views.votingSheet_validate, name = "voting-sheet-validate"),
    

    path('ajax/load-towns/', views.load_towns, name='ajax_load_towns'), # AJAX

    
]

remotevote/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "CEE Administrator"
admin.site.site_title = "CEE Admin Portal"
admin.site.index_title = "Portal de Administración CEE"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("census.urls")),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

census/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import AuthenticationForm

# Create your models here.

class Padron(models.Model):
    cic = models.CharField(max_length=9, primary_key=True, unique=True)
    curp = models.CharField(max_length=18)
    name = models.CharField(max_length=40)
    lastName = models.CharField(max_length=40)
    momLastName = models.CharField(max_length=40)
    birthDate = models.CharField(max_length = 10)
    mail = models.CharField(max_length=20)
    phoneNumber = models.CharField(max_length=20)
    postalCode = models.IntegerField()
    town = models.CharField(max_length=40)
    state = models.CharField(max_length=40)
    gender = models.CharField(max_length=2)
    secQuestion1 = models.CharField(max_length=80)
    secAns1 = models.CharField(max_length=20)
    secQuestion2 = models.CharField(max_length=80)
    secAns2 = models.CharField(max_length=20)
    secQuestion3 = models.CharField(max_length=80)
    secAns3 = models.CharField(max_length=20)
    faceImage1 = models.ImageField(upload_to='images/')
    faceImage2 = models.ImageField(upload_to='images/')
    faceImage3 = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.cic

class State(models.Model):
    state = models.CharField(max_length=50)
    code = models.IntegerField()
    def __str__(self):
        return self.state 

class Town(models.Model):
    town = models.CharField(max_length=50)
    code = models.CharField(max_length=4)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    def __str__(self):
        return self.town 

class SecurityQuestion(models.Model):
    question = models.CharField(max_length=200)
    def __str__(self):
        return self.question 

class PoliticalParty(models.Model):

    partyName = models.CharField(max_length=50)
    partyLogo = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.partyName

census/views.py
from django.shortcuts import render
from django.contrib.auth import logout, login
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.forms import formset_factory
from bson import ObjectId
import utils
from .forms import *
from .models import *

# Create your views here.

db = utils.get_db_handle("mongodb://localhost:27017", "election")


# Home
def home(request):

    '''
    db = utils.get_db_handle("mongodb://localhost:27017", "election")
    electionDB = db["vote_sheets"]

    electionDB.insert_one({
        "startDate": "2023/06/06",
        "endDate": "2023/06/08",
        "electionName": "Eleccion de Presidente",
        "electionType": "Presidencial",
        "electionStatus": "Activa",
        "electionDescription": "Eleccion de Presidente de la Republica Mexicana",
        "electionCandidates": [{

                "candidateName": "Andres Manuel Lopez Obrador",
                "candidateParty": "Morena",
                "candidateDescription": "Candidato a la Presidencia de la Republica Mexicana", 
                
                }],
    })
    '''
    
    return render(request, "empadron/home.html")

# /////////// Core Views ///////////

@login_required(login_url="/")
def empadron(request):

    if request.method == "POST":

        if request.user.is_authenticated:

            empadron_form = Empadronamiento(request.POST, request.FILES)
            context = {
                "title": "Empadronamiento de Usuarios",
                "form": empadron_form
            }

            if empadron_form.is_valid():
                print("FORM VALID!")

                data = empadron_form.cleaned_data

                print(data)

                Padron.objects.create(
                    cic = data["cic"],
                    curp = data["curp"],
                    name = data["name"],
                    lastName = data["lastName"],
                    momLastName = data["momLastName"],
                    birthDate = data["birthDate"],
                    mail = data["mail"],
                    phoneNumber = data["phoneNumber"],
                    postalCode = data["postalCode"],
                    town = data["town"],
                    state = data["state"],
                    gender = data["gender"],
                    secQuestion1 = data["secQuestion1"],
                    secAns1 = data["secAns1"],
                    secQuestion2 = data["secQuestion2"],
                    secAns2 = data["secAns2"],
                    secQuestion3 = data["secQuestion3"],
                    secAns3 = data["secAns3"],
                    faceImage1 = request.FILES["faceImage1"],
                    faceImage2 = request.FILES["faceImage2"],
                    faceImage3 = request.FILES["faceImage3"],
                )

                return redirect("empadron")
            
        
            return render(request, "empadron/form.html", context)
    
    else:
        empadron_form = Empadronamiento()
        context = {
            "title": "Empadronamiento de Usuarios",
            "form": empadron_form
        }

        return render(request, "empadron/form.html", context)

@login_required(login_url="/")
def votingSheet(request):
    return render(request, "votingSheet/menu.html")


@login_required(login_url="/")
def votingSheet_generate(request):

    if request.method == "POST":
    
            votingSheet_form = VoteSheetsCreate(request.POST)
            context = {
                "form": votingSheet_form
            }

            # print(votingSheet_form.is_valid())

            # print(votingSheet_form.cleaned_data)

            if votingSheet_form.is_valid():
                print("FORM VALID!")

                electionDB = db["vote_sheets"]

                data = votingSheet_form.cleaned_data

                votingSheet_form.cleaned_data["electionDateStart"] = votingSheet_form.cleaned_data["electionDateStart"].strftime("%Y/%m/%d")
                votingSheet_form.cleaned_data["electionDateEnd"] = votingSheet_form.cleaned_data["electionDateEnd"].strftime("%Y/%m/%d")

                votingSheet_form.cleaned_data["electionTimeStart"] = votingSheet_form.cleaned_data["electionTimeStart"].strftime("%H:%M")
                votingSheet_form.cleaned_data["electionTimeEnd"] = votingSheet_form.cleaned_data["electionTimeEnd"].strftime("%H:%M")

                sheet = electionDB.insert_one(data)

                return redirect('voting-sheet-fill', id_sheet = str(sheet.inserted_id))

            return render(request, "votingSheet/voting_sheets_generate.html", context)
                                   
    else:
        votingSheet_form = VoteSheetsCreate()
        context = {
            "form": votingSheet_form
        }

        return render(request, "votingSheet/voting_sheets_generate.html", context)

@login_required(login_url="/")
def votingSheet_fill(request, id_sheet):

    electionDB = db["vote_sheets"]
    sheet = electionDB.find_one({"_id": ObjectId(id_sheet) })
    candidates = sheet["electionCandidatesNumber"]

    fillFormSet = formset_factory(VoteSheetsFill, extra=candidates)
    formSet = fillFormSet()

    context = {
        "formSet": formSet,
        "sheet_id": id_sheet,
        "candidates": candidates,
    }

    if request.method == "POST":

        formSet = fillFormSet(request.POST)

        context = {
            "formSet": formSet,
            "sheet_id": id_sheet,
            "candidates": candidates,
        }

        if formSet.is_valid():
            print("FORM VALID!")
            for form in formSet:
                print(form.cleaned_data)

    return render(request, "votingSheet/voting_sheets_fill.html", context)
    


@login_required(login_url="/")
def votingSheet_candidates(request):
    pass

@login_required(login_url="/")
def votingSheet_validate(request):
    pass

@login_required(login_url="/")
def votingSheet_history(request):
    
    if request.method == "POST":
    
            if request.user.is_authenticated:
    
                votingSheet_form = VoteSheetsChecker(request.POST)
                context = {
                    "form": votingSheet_form
                }
    
                if votingSheet_form.is_valid():
                    print("FORM VALID!")
                    data = votingSheet_form.cleaned_data  

                    context = {
                        # vote sheet id and other fields to pass to other page
                    }
                
                return render(request, "votingSheet/history_sheets.html", context)
        
    else:
        votingSheet_form = VoteSheetsChecker()
        context = {
            "form": votingSheet_form
        }

        return render(request, "votingSheet/history_sheets.html", context)


# /////////// Login Views ///////////

def log_in(request):

    if request.user.is_authenticated:
        return redirect("empadron")

    if request.method == 'POST':
        form = AuthenticationForm(request = request, data = request.POST)

        if form.is_valid():
            user = authenticate(
                username = form.cleaned_data["username"],
                password = form.cleaned_data["password"]
            )

            if user is not None:
                login(request, user)
                messages.success(request, f"Inicio de Sesion Correcto!")
                return redirect("empadron")
        
        else:
            messages.error(request, "Usuario o Contraseña Incorrectos. Los campos son sensibles a mayusculas o minusculas")
    
    form = LoginForm()

    return render(
        request,
        template_name="empadron/login.html",
        context={
            "form" : form
        }
    )

@login_required(login_url="/")
def log_out(request):
    
    logout(request)
    messages.info(request, "Cierre de Sesion Exitoso")
    return render(request, "empadron/logout.html")

# /////////// AJAX Views ///////////            

def load_towns(request):
    state_id = request.GET.get('state')
    towns = Town.objects.filter(state_id = state_id).order_by('town')
    return render(request, "empadron/towns_dropdown.html", {'towns': towns})

census/templates/empadron/form.html
{% extends "layouts/header.html"%}

{% load crispy_forms_tags %}

{% block content %}

    {% load static %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Empadronamiento</title>

        <link href = "{% static 'styles/form.css' %}" rel = "stylesheet">
        <link href = "{% static 'styles/icons/fonts.css' %}" rel = "stylesheet">

    </head>
    <body>
        
        <h1 id="title">Registro de Nuevos Usuarios</h1>

        <form method="POST" id="reg_form" data-towns-url="{% url 'ajax_load_towns' %}" enctype="multipart/form-data" novalidate >

            {% csrf_token %}

            <div class="form-elements">

                <div id="form-item">
                    <label for="cic">CIC*</label>
                    {{ form.cic}}
                    <span style="color: red; font-size: 10px;">{{ form.errors.cic }}</span>
                </div>
                
                <div id="form-item">
                    <label for="curp">CURP*</label>
                    {{ form.curp }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.curp }}</span>
                </div>

                <div id="form-item">
                    <label for="name">Nombre*</label>
                    {{ form.name }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.name }}</span>
                </div>

                <div id="form-item">
                    <label for="lastName">Apellido Paterno*</label>
                    {{ form.lastName }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.lastName }}</span>
                </div>

                <div id="form-item">
                    <label for="secondLastName">Apellido Materno</label>
                    {{ form.momLastName }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.momLastName }}</span>
                </div>

                <div id="form-item">
                    <label for="birthDate">Fecha de Nacimiento*</label>
                    {{ form.birthDate }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.birthDate }}</span>
                </div>

                <div id="form-item">
                    <label for="email">Correo Electrónico*</label>
                    {{ form.mail }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.mail }}</span>
                </div>

                <div id="form-item">
                    <label for="phoneNumber">Teléfono*</label>
                    {{ form.phoneNumber }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.phoneNumber }}</span>
                </div>

                <div id="form-item">
                    <label for="postalCode">Código Postal*</label>
                    {{ form.postalCode }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.postalCode }}</span>
                </div>

                <div id="form-item">
                    <label for="state">Estado*</label>
                    {{ form.state }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.state }}</span>
                </div>

                <div id="form-item">
                    <label for="town">Municipio*</label>
                    {{ form.town }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.town }}</span>
                </div>

                <div id="form-item">
                    <label for="gender">Genero*</label>
                    {{ form.gender }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.gender }}</span>
                </div>

                <div id="form-item">
                    <label for="secQuestion1">Pregunta de Seguridad 1*</label>
                    {{ form.secQuestion1 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.secQuestion1 }}</span>
                </div>

                <div id="form-item">
                    <label for="secAns1">Respuesta a Pregunta de Seguridad 1*</label>
                    {{ form.secAns1 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.secAns1 }}</span>
                </div>

                <div id="form-item">
                    <label for="secQuestion2">Pregunta de Seguridad 2*</label>
                    {{ form.secQuestion2 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.secQuestion2 }}</span>
                </div>

                <div id="form-item">
                    <label for="secAns2">Respuesta a Pregunta de Seguridad 2*</label>
                    {{ form.secAns2 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.secAns2 }}</span>
                </div>

                <div id="form-item">
                    <label for="secQuestion3">Pregunta de Seguridad 3*</label>
                    {{ form.secQuestion3 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.secQuestion3 }}</span>
                </div>

                <div id="form-item">
                    <label for="secAns3">Respuesta a Pregunta de Seguridad 3*</label>
                    {{ form.secAns3 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.secAns3 }}</span>
                </div>

                <div id="form-item">
                    <label for="faceImage1">Imagen Rostro Numero 1*</label>
                    {{ form.faceImage1 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.faceImage1 }}</span>
                </div>

                <div id="form-item">
                    <label for="faceImage2">Imagen Rostro Numero 2*</label>
                    {{ form.faceImage2 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.faceImage2 }}</span>
                </div>

                <div id="form-item">
                    <label for="faceImage3">Imagen Rostro Numero 3*</label>                    
                    {{ form.faceImage3 }}
                    <span style="color: red; font-size: 10px;">{{ form.errors.faceImage3 }}</span>
                </div>

                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script>
                    $("#id_state").change(function () {
                    var url = $("#reg_form").attr("data-towns-url");  // get the url of the `load_cities` view
                    var stateId = $(this).val();  // get the selected country ID from the HTML input

                    $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                        data: {
                        'state': stateId       // add the country id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_town").html(data);  // replace the contents of the city input with the data that came from the server
                        }
                    });

                    });
                </script>


            
            <button class="btn btn-warning">Guardar</button>

        </form>
        
    </body>
    </html>

{% endblock %}

census/templates/empadron/home.html
{% include "layouts/header.html"%}


{% block content %}

    {% load static %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio</title>

        <link href = "{% static 'styles/home.css' %}" rel = "stylesheet">

    </head>
    <body>

        <p class = "title">Portal para Colaboradores CEE </p>
        <p class = "subtitle"> Selecciona una de las opciones del menu para continuar </p>

    </body>
    </html>

{% endblock %}

census/templates/empadron/login.html
{% include "layouts/header.html"%}

{% block content %}

    {% load static %}

    <!DOCTYPE html>
    <html lang="en">
    <head>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Acceso a Colaboradores</title>

        <link href = "{% static 'styles/login.css' %}" rel = "stylesheet">
        <link href = "{% static 'styles/icons/fonts.css' %}" rel = "stylesheet">

    </head>
    <body>

        <div class = "login-form container-fluid align-center">

            <p class = "title">Bienvenido!</p>

            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.password }}
                </div>

                <div class="btn-group">
                    
                    <button class="btn btn-primary" type="submit">Ingresar</button>

                </div>

                
            
            </form>

        </div>

    </body>
    </html>

{% endblock %}

census/templates/empadron/logout.html
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

census/templates/empadron/towns_dropdown.html
<div id="form-item">
    <option name = "town" id = "id_town" class = "form-control" value="">---------</señ>
    {% for town in towns %}
    <option name = "town" id = "id_town" class = "form-control" value="{{ town.pk }}">{{ town.town }}</option>
    {% endfor %}
</div>